config/routes.rb
PasokaraPlayerRails3::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'custom_devise/sessions', :registrations => 'custom_devise/registrations'}, :skip => [:sessions, :registrations]
  devise_scope :user do
    get '/users/sign_in', :to => 'custom_devise/sessions#new', :as => :new_user_session
    post '/users/sign_in', :to => 'custom_devise/sessions#create', :as => :user_session
    get '/users/sign_out', :to => 'custom_devise/sessions#destroy', :as => :destroy_user_session
    get '/users/switch/:id', :to => 'custom_devise/sessions#switch', :as => :switch_user_session

    get '/users/cancel', :to => 'custom_devise/registrations#cancel', :as => :cancel_user_registration
    get '/users/sign_up', :to => 'custom_devise/registrations#new', :as => :new_user_registration
    post '/users', :to => 'custom_devise/registrations#create', :as => :user_registration
    get '/users/edit', :to => 'custom_devise/registrations#edit', :as => :edit_user_registration
    put '/users', :to => 'custom_devise/registrations#update'
    delete '/users', :to => 'custom_devise/registrations#destroy'
  end

  authenticate :user do
    mount Resque::Server.new, :at => "/resque"
  end

  resources :directories, :only => [:index, :show]
  resources :history, :only => [:index]
  resources :nico_lists
  resources :queues, :only => [:index, :destroy] do
    collection do
      get 'deque'
      get 'last'
    end
  end

  resources :tags, :only => [:index] do
    collection do
      post 'search'
    end
  end

  resources :pasokaras, :only => [:index, :show] do
    member do
      get 'thumb'
      get 'queue'
      get 'preview'
      get 'raw_file'
      get 'movie_path'
      get 'encode_status'
      get 'add_favorite'
      get 'remove_favorite'
    end

    collection do
      get 'search'
      post 'search'
      get 'favorite'
      post 'favorite'
      get 'play'
      get 'change_encode_mode'
    end
  end

  match 'help/usage' => 'help#usage'

  root :to => "directories#index"

end

app/models/nico_list.rb
class NicoList
  include Mongoid::Document
  include Mongoid::Timestamps
  field :url, :type => String
  field :download, :type => Boolean, :default => true

  validates_presence_of :url
  validates_uniqueness_of :url
end

app/controllers/nico_lists_controller.rb
# coding: utf-8
class NicoListsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_check

  # GET /nico_lists
  # GET /nico_lists.json
  def index
    @nico_list = NicoList.new
    @nico_lists = NicoList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @nico_lists }
    end
  end

  # GET /nico_lists/1
  # GET /nico_lists/1.json
  def show
    @nico_list = NicoList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @nico_list }
    end
  end

  # GET /nico_lists/new
  # GET /nico_lists/new.json
  def new
    @nico_list = NicoList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @nico_list }
    end
  end

  # GET /nico_lists/1/edit
  def edit
    @nico_list = NicoList.find(params[:id])
  end

  # POST /nico_lists
  # POST /nico_lists.json
  def create
    @nico_list = NicoList.new(params[:nico_list])

    respond_to do |format|
      if @nico_list.save
        format.html {
          flash[:notice] = 'ダウンロードリストが追加されました'
          redirect_to(nico_lists_path)
        }
        format.js {
          html_str = render_to_string "_row", :locals => {:nico_list => @nico_list}
          render :text => html_str
        }
        format.json { render :json => @nico_list, :status => :created }
      else
        format.html { render :action => "new" }
        format.js   { render :json => @nico_list.errors, :status => :unprocessable_entity }
        format.json { render :json => @nico_list.errors, :status => :unprocessable_entity  }
      end
    end
  end

  # PUT /nico_lists/1
  # PUT /nico_lists/1.json
  def update
    @nico_list = NicoList.find(params[:id])

    respond_to do |format|
      if @nico_list.update_attributes(params[:nico_list])
        format.html { redirect_to(@nico_list, :notice => 'Nico list was successfully updated.') }
        format.json { render :json => @nico_list }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @nico_list.errors, :status => :unprocessable_entity  }
      end
    end
  end

  # DELETE /nico_lists/1
  # DELETE /nico_lists/1.json
  def destroy
    @nico_list = NicoList.find(params[:id])
    @nico_list.destroy

    respond_to do |format|
      format.html { redirect_to(nico_lists_url) }
      format.json  { head :ok }
    end
  end

  private
  def admin_check
    unless current_user.try(:admin)
      redirect_to root_url
      false
    end
  end
end

app/helpers/nico_lists_helper.rb
module NicoListsHelper
end

app/views/nico_lists/_form.html.haml
= form_for @nico_list do |f|
  -if @nico_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@nico_list.errors.count, "error")} prohibited this nico_list from being saved:"
      %ul
        - @nico_list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :download
    = f.check_box :download
  .actions
    = f.submit 'Save'

app/views/nico_lists/_row.html.haml
= form_for nico_list, :format => :json, :remote => true do |f|
  %tr{:id => "nico_list_#{nico_list.id}"}
    %td= f.text_field :url, :class => "nico_list_url", :id => "nico_list_url_#{nico_list.id}", :size => 40
    %td= f.check_box :download, :class => "nico_list_download", :id => "nico_list_download_#{nico_list.id}"
    %td= f.submit
    %td= link_to '削除する', nico_list, :confirm => 'Are you sure?', :method => :delete

app/views/nico_lists/edit.html.haml
%h1 Editing nico_list

= render 'form'

= link_to 'Show', @nico_list
\|
= link_to 'Back', nico_lists_path

app/views/nico_lists/index.html.haml
%h1 ニコニコ動画ダウンロードリスト

#new_nico_list_box
  = link_to '新規リスト追加', new_nico_list_path
= form_for @nico_list, :remote => true, :format => :js, :html => {:data => {:type => "text"}} do |f|
  %table#new_nico_list_table
    %thead
      %tr
        %th Url
        %th Download
        %th
    %tbody
      %tr
        %td= f.text_field :url, :size => 40
        %td= f.check_box :download
        %td= f.submit

%table#nico_list_table
  %thead
    %tr
      %th Url
      %th Download
      %th
      %th
  %tbody
    - @nico_lists.each do |nico_list|
      = render 'row', :nico_list => nico_list

app/views/nico_lists/new.html.haml
%h1 New nico_list

= render 'form'

= link_to 'Back', nico_lists_path

app/views/nico_lists/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @nico_list.url

= link_to 'Edit', edit_nico_list_path(@nico_list)
\|
= link_to 'Back', nico_lists_path