config/routes.rb
PasokaraPlayerRails3::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'custom_devise/sessions', :registrations => 'custom_devise/registrations'}, :skip => [:sessions, :registrations]
  devise_scope :user do
    get '/users/sign_in', :to => 'custom_devise/sessions#new', :as => :new_user_session
    post '/users/sign_in', :to => 'custom_devise/sessions#create', :as => :user_session
    get '/users/sign_out', :to => 'custom_devise/sessions#destroy', :as => :destroy_user_session
    get '/users/switch/:id', :to => 'custom_devise/sessions#switch', :as => :switch_user_session

    get '/users/cancel', :to => 'custom_devise/registrations#cancel', :as => :cancel_user_registration
    get '/users/sign_up', :to => 'custom_devise/registrations#new', :as => :new_user_registration
    post '/users', :to => 'custom_devise/registrations#create', :as => :user_registration
    get '/users/edit', :to => 'custom_devise/registrations#edit', :as => :edit_user_registration
    put '/users', :to => 'custom_devise/registrations#update'
    delete '/users', :to => 'custom_devise/registrations#destroy'
  end

  authenticate :user do
    mount Resque::Server.new, :at => "/resque"
  end

  resources :directories, :only => [:index, :show]
  resources :history, :only => [:index]
  resources :nico_lists
  resources :queues, :only => [:index, :destroy] do
    collection do
      get 'deque'
      get 'last'
    end
  end

  resources :tags, :only => [:index] do
    collection do
      post 'search'
    end
  end

  resources :pasokaras, :only => [:index, :show] do
    member do
      get 'thumb'
      get 'queue'
      get 'preview'
      get 'raw_file'
      get 'movie_path'
      get 'encode_status'
      get 'add_favorite'
      get 'remove_favorite'
    end

    collection do
      get 'search'
      post 'search'
      get 'favorite'
      post 'favorite'
      get 'play'
      get 'change_encode_mode'
    end
  end

  match 'help/usage' => 'help#usage'

  root :to => "directories#index"

end

app/models/tag.rb
class Tag
  include Mongoid::Document
  field :name, :type => String
  field :size, :type => Integer, :default => 0
  index({name: 1}, {unique: true})
  index({size: 1})

  validates_presence_of :name

  paginates_per 50

  def count
    size
  end

  # sunspotのfacetとインターフェースを合わせるため
  def value
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :no_tag_load
  # GET /tags
  # GET /tags.xml
  def index
    @tags = Tag.order_by([[:size, :desc]]).page params[:page]

    respond_to do |format|
      format.html
      format.xml  { render :xml => @tags }
      format.json { render :json => @tags }
    end
  end

  def search
    @tags = Tag.order_by([[:size, :desc]]).where(name: /#{Regexp.escape(params[:tag])}/).page params[:page]

    respond_to do |format|
      format.html { render :action => "index" }
      format.js
      format.xml  { render :xml => @tags }
      format.json { render :json => @tags }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.haml
= image_tag("icon/home.png", :class => "icon", :size => "36x36")
= link_to("Go Top Directory", root_path)
%h1= image_tag("icon/search.png", :class => "icon", :size => "32x32") + "タグ一覧"
= form_tag(search_tags_path, :remote => true) do
  %label{:for=>"tag"} タグを検索する: 
  = text_field_tag "tag", "", :size => 16
  = submit_tag "検索"

#entity_list
  .autopagerize_page_element
    %ul
      - @tags.each do |t|
        = entity_li(t)

= paginate @tags
%br

= image_tag("icon/home.png", :class => "icon", :size => "36x36")
= link_to("Go Top Directory", root_path)

app/views/tags/search.js.haml
- entities = @tags.inject(""){ |str, t| str += j(entity_li(t)) }
$("#entity_list ul").empty().append("#{entities}");

$("nav.pagination").replaceWith("#{j(paginate(@tags))}");