config/routes.rb
PasokaraPlayerRails3::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'custom_devise/sessions', :registrations => 'custom_devise/registrations'}, :skip => [:sessions, :registrations]
  devise_scope :user do
    get '/users/sign_in', :to => 'custom_devise/sessions#new', :as => :new_user_session
    post '/users/sign_in', :to => 'custom_devise/sessions#create', :as => :user_session
    get '/users/sign_out', :to => 'custom_devise/sessions#destroy', :as => :destroy_user_session
    get '/users/switch/:id', :to => 'custom_devise/sessions#switch', :as => :switch_user_session

    get '/users/cancel', :to => 'custom_devise/registrations#cancel', :as => :cancel_user_registration
    get '/users/sign_up', :to => 'custom_devise/registrations#new', :as => :new_user_registration
    post '/users', :to => 'custom_devise/registrations#create', :as => :user_registration
    get '/users/edit', :to => 'custom_devise/registrations#edit', :as => :edit_user_registration
    put '/users', :to => 'custom_devise/registrations#update'
    delete '/users', :to => 'custom_devise/registrations#destroy'
  end

  authenticate :user do
    mount Resque::Server.new, :at => "/resque"
  end

  resources :directories, :only => [:index, :show]
  resources :history, :only => [:index]
  resources :nico_lists
  resources :queues, :only => [:index, :destroy] do
    collection do
      get 'deque'
      get 'last'
    end
  end

  resources :tags, :only => [:index] do
    collection do
      post 'search'
    end
  end

  resources :pasokaras, :only => [:index, :show] do
    member do
      get 'thumb'
      get 'queue'
      get 'preview'
      get 'raw_file'
      get 'movie_path'
      get 'encode_status'
      get 'add_favorite'
      get 'remove_favorite'
    end

    collection do
      get 'search'
      post 'search'
      get 'favorite'
      post 'favorite'
      get 'play'
      get 'change_encode_mode'
    end
  end

  match 'help/usage' => 'help#usage'

  root :to => "directories#index"

end

app/controllers/pasokaras_controller.rb
# coding: utf-8
class PasokarasController < ApplicationController
  before_filter :top_tag_load, :except => [:search, :thumb]
  before_filter :authenticate_user!, :only => [:queue, :preview, :add_favorite, :favorite_list]

  def index
    @pasokaras = PasokaraFile.only(:id, :name, :nico_name, :duration).all
    respond_to do |format|
      format.xml {render :xml => @pasokaras}
      format.json {render :json => @pasokaras}
      format.text {render :text => @pasokaras.map {|pasokara| pasokara.nico_name }.compact.join("\n")}
    end
  end

  def queue
    if params[:id] =~ /sm\d+/
      @pasokara = PasokaraFile.only(:id, :name, :nico_name, :duration, :fullpath).where(nico_name: params[:id])[0]
    elsif params[:id] =~ /^[\w\d]+$/
      @pasokara = PasokaraFile.only(:id, :name, :nico_name, :duration, :fullpath).find(params[:id])
    else
      render :text => "パラメーターが不正です。", :status => 404 and return
    end
    QueuedFile.enq @pasokara, current_user

    if !@pasokara.encoded?(session[:encode_mode])
      @pasokara.do_encode(nil, session[:encode_mode]) if Rails.env != "test"
    end

    @message = "#{@pasokara.name} の予約が完了しました"
    respond_to do |format|
      format.html {
        flash[:notice] = @message
        redirect_to root_path
      }
      format.js
      format.xml { render :xml => @message.to_xml }
      format.json { render :json => {:message => @message}.to_json }
    end
  end

  def change_encode_mode
    session[:encode_mode] = session[:encode_mode] == :webm ? :safari : :webm
    redirect_to root_url
  end

  def movie_path
    @pasokara = PasokaraFile.find(params[:id])
    type = params[:type] ? params[:type].to_sym : :webm
    @movie_path = type == :raw ? @pasokara.movie_path : @pasokara.encode_filepath(type)
    respond_to do |format|
      format.json {render :json => {:path => @movie_path, :type => type}.to_json}
    end
  end

  def encode_status
    @pasokara = PasokaraFile.find(params[:id])
    type = params[:type] ? params[:type].to_sym : :webm
    status = type == :raw ? true : @pasokara.encoded?(type)
    respond_to do |format|
      format.json {
        data = {
          :id => @pasokara.id,
          :path => @pasokara.encode_filepath(type),
          :type => type,
          :status => status
        }
        render :json => data.to_json
      }
    end
  end

  def raw_file
    @pasokara = PasokaraFile.find(params[:id])
    case @pasokara.extname
    when ".mp4"
      type = "video/mp4"
    when ".flv"
      type = "video/x-flv"
    else
      type = "application/octet-stream"
    end
    send_file(@pasokara.fullpath, :filename => "#{@pasokara.name}#{@pasokara.extname}")
  end

  def preview
    @pasokara = PasokaraFile.find(params[:id])
    if request.all_safari?
      unless @pasokara.encoded?(:safari)
        @pasokara.do_encode(nil, :safari)
      end
      @movie_path = @pasokara.encode_filepath(:safari)
      @type = "safari"
    else
      unless @pasokara.encoded?(:webm)
        @pasokara.do_encode(nil, :webm)
      end
      @movie_path = @pasokara.encode_filepath(:webm)
      @type = "webm"
    end

    render :action => "preview"
  end

  def play
    if params[:deque]
      QueuedFile.first.destroy
    end
    @queue = QueuedFile.deq
    @queue_list = QueuedFile.scoped
    if @queue
      @pasokara = @queue.pasokara_file
      @type = request.all_safari? ? :safari : :webm
      unless @pasokara.encoded?(@type)
        @pasokara.do_encode(nil, @type)
      end
      @movie_path = @pasokara.encode_filepath(@type)

      respond_to do |format|
        format.html { render :action => "play", :layout => false }
        format.json { render :json => {:id => @pasokara.id, :path => @movie_path, :type => @type}.to_json }
      end
    else
      respond_to do |format|
        format.html { render :action => "play", :layout => false }
        format.json { render :json => {}.to_json, :status => 404 }
      end
    end
  end

  def favorite
    unless current_user.favorite
      current_user.create_favorite
    end
    @pasokaras = current_user.favorite.pasokara_files.order_by(mongoid_order_options).page params[:page]

    respond_to do |format|
      format.html { render :stream => true }
      format.js
      format.xml { render :xml => @search.results.to_xml }
      format.json { render :json => @search.results.to_json }
    end
  end

  def add_favorite
    @pasokara = PasokaraFile.find(params[:id])
    if current_user.favorite? @pasokara
      @message = "#{@pasokara.name}は既に#{current_user.nickname}のお気に入りに登録済みです"
    else
      current_user.add_favorite @pasokara
      @message = "#{@pasokara.name}を#{current_user.nickname}のお気に入りに追加しました"
    end

    respond_to do |format|
      format.html {
        flash[:notice] = @message
        redirect_to root_path
      }
      format.js {render :action => 'queue'}
      format.xml { render :xml => @message.to_xml }
      format.json { render :json => {:message => @message}.to_json }
    end
  end

  def remove_favorite
    @pasokara = PasokaraFile.find(params[:id])
    current_user.favorite.pasokara_file_ids.delete @pasokara.id
    current_user.favorite.save!

    @message = "#{@pasokara.name}を#{current_user.nickname}のお気に入りから削除しました"
    respond_to do |format|
      format.html {
        flash[:notice] = @message
        redirect_to root_path
      }
      format.js
      format.xml { render :xml => @message.to_xml }
      format.json { render :json => {:message => @message}.to_json }
    end
  end

  def search
    @query = params[:query]
    @filters = params[:filter] ? params[:filter].split(/\+/) : nil

    if !@query.blank?
      queries = @query.split(/\s+/)
      case params[:field]
      when "n"
        @search = solr_name_search(queries, @filters)
      when "t"
        @search = solr_tag_search(queries, @filters)
      when "d"
        @search = solr_desc_search(queries, @filters)
      when "r"
        @search = solr_raw_search(@query, @filters)
      when "a"
        @search = solr_all_search(queries, @filters)
      else
        @search = solr_name_search(queries, @filters)
      end
    else
      @search = solr_noquery_search(@filters)
    end

    @header_tags = @search.facet(:tags).rows

    respond_to do |format|
      format.html { render :stream => true }
      format.js
      format.xml { render :xml => @search.results.to_xml }
      format.json { render :json => @search.results.to_json }
    end
  end

  protected
  def solr_noquery_search(filters = nil)
    tag_filter = nil
    sort_order = solr_order_options
    search = Sunspot.search PasokaraFile do
      paginate(:page => params[:page], :per_page => per_page)
      if filters
        tag_filter = with(:tags).all_of filters
      end
      order_by sort_order[0], sort_order[1]
      facet :tags, :limit => 50
    end
  end

  def solr_name_search(queries, filters = nil)
    tag_filter = nil
    sort_order = solr_order_options
    search = Sunspot.search PasokaraFile do
      keywords(queries, :fields => [:name])
      paginate(:page => params[:page], :per_page => per_page)
      if filters
        tag_filter = with(:tags).all_of filters
      end
      order_by sort_order[0], sort_order[1]
      facet :tags, :limit => 50
    end
  end

  def solr_tag_search(queries, filters = nil)
    sort_order = solr_order_options
    search = Sunspot.search PasokaraFile do
      if filters
        tag_filter = with(:tags).all_of (queries + filters).uniq
      else
        tag_filter = with(:tags).all_of queries
      end
      paginate(:page => params[:page], :per_page => per_page)
      order_by sort_order[0], sort_order[1]
      facet :tags, :limit => 50
    end
  end

  def solr_desc_search(queries, filters = nil)
    tag_filter = nil
    sort_order = solr_order_options
    search = Sunspot.search PasokaraFile do
      keywords(queries, :fields => [:nico_description])
      paginate(:page => params[:page], :per_page => per_page)
      if filters
        tag_filter = with(:tags).all_of filters
      end
      order_by sort_order[0], sort_order[1]
      facet :tags, :limit => 50
    end
  end

  def solr_raw_search(query, filters = nil)
    tag_filter = nil
    sort_order = solr_order_options
    search = Sunspot.search PasokaraFile do
      adjust_solr_params do |p|
        p[:q] = query
      end
      paginate(:page => params[:page], :per_page => per_page)
      if filters
        tag_filter = with(:tags).all_of filters
      end
      order_by sort_order[0], sort_order[1]
      facet :tags, :limit => 50
    end
  end

  def solr_all_search(queries, filters = nil)
    tag_filter = nil
    sort_order = solr_order_options
    solr_queries_temp = []
    solr_queries_temp << queries.map {|w| "name:#{w}"}.join(" AND ")
    solr_queries_temp << queries.map {|w| "tags:#{w}"}.join(" AND ")
    solr_queries_temp << queries.map {|w| "nico_description:#{w}"}.join(" AND ")
    solr_queries = solr_queries_temp.map {|q| "(#{q})"}.join(" OR ")
    search = Sunspot.search PasokaraFile do
      adjust_solr_params do |p|
        p[:q] = solr_queries
      end
      paginate(:page => params[:page], :per_page => per_page)
      if filters
        tag_filter = with(:tags).all_of filters
      end
      order_by sort_order[0], sort_order[1]
      facet :tags, :limit => 50
    end
  end

  def set_solr_query(query)
    words = query.split(/\s+/)
    if words.empty?
      return "*.*"
    end

    case params[:field]
    when "n"
      solr_query = words.join(" AND ")
    when "t"
      solr_query = words.map {|w| "tag:#{w}"}.join(" AND ")
    when "d"
      solr_query = words.map {|w| "nico_description:#{w}"}.join(" AND ")
    when "r"
      solr_query = @query
    when "a"
      solr_query_temp = []
      solr_query_temp << words.map {|w| "name:#{w}"}.join(" AND ")
      solr_query_temp << words.map {|w| "tag:#{w}"}.join(" AND ")
      solr_query_temp << words.map {|w| "nico_description:#{w}"}.join(" AND ")
      solr_query = solr_query_temp.map {|q| "(#{q})"}.join(" OR ")
    else

app/helpers/pasokaras_helper.rb
module PasokarasHelper
end

app/views/pasokaras/_pasokara_file_list.html.haml
- pasokaras.each do |pasokara|
  %li.pasokara_file[pasokara]
    .title
      = image_tag("icon/music_48x48.png", :size => @icon_size, :class=> "icon")
      - if current_user
        = link_to(pasokara.name, queue_pasokara_path(pasokara), :remote => true, :confirm => "#{pasokara.name}を予約に追加しますか？", :class => "queue_link")
        = link_to("[プレビュー]", preview_pasokara_path(pasokara), :class => "preview_link", :target => "_blank")
        %span.duration= pasokara.duration_str
        = link_to(image_tag("icon/star_off_48.png", :size => "24x24"), add_favorite_pasokara_path(pasokara), :remote => true, :confirm => "#{pasokara.name}を#{current_user.nickname}のお気に入りに追加しますか？", :id => "add_favorite_#{pasokara.id}", :class => "add_favorite")
      - else
        %span.title= pasokara.name
        %span.preview [プレビュー]

    %div{:id => "info-box-#{pasokara.id}", :class => "info_box"}
      %h3 タグ
      %div{:id => "tag-list-#{pasokara.id}", :class => "tag_list"}
        - pasokara.tag_list.each do |tag_name|
          %span.tag= link_to(tag_name, search_pasokaras_path(:query => tag_name, :field => "t"))
      %hr
      %h3 動画情報
      %div{:id => "info-list-#{pasokara.id}", :class => "info_list"}
        %div{:class => ["thumb", "clearfix"]}
          = image_tag(image_path("gray.gif"), :data => {:original => pasokara.thumbnail.url}, :size => "160x120", :class => "thumb")
        %div{:class => ["nico_info", "clearfix"]}
          %span.info_key> ニコニコID:
          %span.info_value>= link_to(pasokara.nico_name, pasokara.nico_url) if pasokara.nico_name
          %br
          %span.info_key> 投稿日:
          %span.info_value>= pasokara.nico_post_str
          %br
          %span.info_key> 再生数:
          %span.info_value>= number_with_delimiter(pasokara.nico_view_counter)
          %br
          %span.info_key> コメント数:
          %span.info_value>= number_with_delimiter(pasokara.nico_comment_num)
          %br
          %span.info_key> マイリスト数:
          %span.info_value>= number_with_delimiter(pasokara.nico_mylist_counter)
          %br

        - if current_user && current_user.favorite?(pasokara)
          = link_to "お気に入りから削除する", remove_favorite_pasokara_path(pasokara), :remote => true, :confirm => "#{pasokara.name}を#{current_user.nickname}のお気に入りから削除しますか？", :style => "color: red;"

app/views/pasokaras/favorite.html.haml
%h1= "#{current_user.nickname}のお気に入り"

= form_tag do
  = hidden_field_tag "query", params[:query]
  = hidden_field_tag "field", params[:field]
  = hidden_field_tag "filter", params[:filter]
  %label{:for => "sort"} ソート:
  = select_tag "sort", options_for_select(PasokaraFile::SORT_OPTIONS, params[:sort])
  = submit_tag "並び替え"

#entity_list
  .autopagerize_page_element
    %ul
      = render :partial => "pasokaras/pasokara_file_list", :locals => {:pasokaras => @pasokaras}

%br

= paginate @pasokaras
%br
= image_tag("icon/home.png", :size => "24x24")
= link_to("Go Top Directory", root_path)

app/views/pasokaras/index.html.haml
%h1 Pasokaras#index
%p Find me in app/views/pasokaras/index.html.haml

app/views/pasokaras/play.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %meta{:content => "noindex,nofollow", :name => "robots"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    - if request.iphone?
      %meta{:content => "width=640, initial-scale=0.5", :name => "viewport"}/
    - elsif request.ipad?
      %meta{:content => "width=640, initial-scale=1.0", :name => "viewport"}/
    %title PasokaraPlayer - Play

    %script{:id => "videoTemplate", :type => "text/x-jquery-tmpl"}
      %video{:id => "videoPlayer", :class => "fullscreen", :width => "640", :height => "480", :controls => "controls", :autoplay => "autoplay", :src => "{{=path}}"}
    %script{:id => "queueListTemplate", :type => "text/x-jquery-tmpl"}
      %li.queue= image_tag("icon/music_48x48.png", :size => "36x36", :class=> "icon") + "{{=name}}"
    - if @pasokara
      :javascript
        $(document).ready(function() {
          indicator_init(true);
          setTimeout(function() {
            check_queue_status();
            check_encode_status({id: "#{@pasokara.id}", path: "#{@movie_path}", type: "#{@type}"}, 0, add_play_video_tag);
          }, 1000);
        });
    - else
      :javascript
        $(document).ready(function() {
          indicator_init(true);
          setTimeout(function() {
            check_queue_status();
            check_next(false);
          }, 1000);
        });
    %body
      %div#indicator{:style => "padding-left: 220px;"}
      #video

      %h2{:style => "color: white;"} 予約一覧
      #queue_table
        %ol

app/views/pasokaras/preview.html.haml
%script{:id => "videoTemplate", :type => "text/x-jquery-tmpl"}
  %video{:id => "videoPlayer", :width => "640", :height => "480", :controls => "controls", :autoplay => "autoplay", :src => "{{=path}}"}

:javascript
  $(document).ready(function() {
    indicator_init();
    check_encode_status({id: "#{@pasokara.id}", path: "#{@movie_path}", type: "#{@type}"}, 0, add_preview_video_tag);
  });

%h1= h @pasokara.name
%div#indicator{:style => "padding-left: 220px;"}
#video{:style => "margin-left: 30px;"}

app/views/pasokaras/preview_smart_phone.html.haml
:javascript
  function add_video_tag(id, path) {
    var video = $("<video>").attr("id", "video-" + id).attr("width", 480).attr("height", 320).attr("controls", "controls").attr("src", path);
    $("#video").append(video);
  }

  $(document).ready(function() {
    indicator_init();
    check_video("#{@pasokara.id}", "#{@movie_path}", add_video_tag);
  });

%h1= h @pasokara.name
%div#indicator{:style => "padding-left: 220px;"}
#video

app/views/pasokaras/queue.js.haml
alert("#{@message}");

app/views/pasokaras/remove_favorite.js.haml
$("pasokara_file_#{@pasokara.id}").fadeOut();

app/views/pasokaras/search.html.haml
%h1= image_tag("icon/search.png", :class => "icon", :size => "32x32") + @query

= form_tag do
  = hidden_field_tag "query", params[:query]
  = hidden_field_tag "field", params[:field]
  = hidden_field_tag "filter", params[:filter]
  %label{:for => "sort"} ソート: 
  = select_tag "sort", options_for_select(PasokaraFile::SORT_OPTIONS, params[:sort])
  = submit_tag "並び替え"

#entity_list
  .autopagerize_page_element
    %ul
      = render :partial => "pasokaras/pasokara_file_list", :locals => {:pasokaras => @search.results}

%br

= paginate @search
%br
= image_tag("icon/home.png", :class => "icon", :size => "24x24")
= link_to("Go Top Directory", root_path)