config/routes.rb
PasokaraPlayerRails3::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => 'custom_devise/sessions', :registrations => 'custom_devise/registrations'}, :skip => [:sessions, :registrations]
  devise_scope :user do
    get '/users/sign_in', :to => 'custom_devise/sessions#new', :as => :new_user_session
    post '/users/sign_in', :to => 'custom_devise/sessions#create', :as => :user_session
    get '/users/sign_out', :to => 'custom_devise/sessions#destroy', :as => :destroy_user_session
    get '/users/switch/:id', :to => 'custom_devise/sessions#switch', :as => :switch_user_session

    get '/users/cancel', :to => 'custom_devise/registrations#cancel', :as => :cancel_user_registration
    get '/users/sign_up', :to => 'custom_devise/registrations#new', :as => :new_user_registration
    post '/users', :to => 'custom_devise/registrations#create', :as => :user_registration
    get '/users/edit', :to => 'custom_devise/registrations#edit', :as => :edit_user_registration
    put '/users', :to => 'custom_devise/registrations#update'
    delete '/users', :to => 'custom_devise/registrations#destroy'
  end

  authenticate :user do
    mount Resque::Server.new, :at => "/resque"
  end

  resources :directories, :only => [:index, :show]
  resources :history, :only => [:index]
  resources :nico_lists
  resources :queues, :only => [:index, :destroy] do
    collection do
      get 'deque'
      get 'last'
    end
  end

  resources :tags, :only => [:index] do
    collection do
      post 'search'
    end
  end

  resources :pasokaras, :only => [:index, :show] do
    member do
      get 'thumb'
      get 'queue'
      get 'preview'
      get 'raw_file'
      get 'movie_path'
      get 'encode_status'
      get 'add_favorite'
      get 'remove_favorite'
    end

    collection do
      get 'search'
      post 'search'
      get 'favorite'
      post 'favorite'
      get 'play'
      get 'change_encode_mode'
    end
  end

  match 'help/usage' => 'help#usage'

  root :to => "directories#index"

end

app/views/layouts/_header_tag_list.html.haml
#all_tag_list
  .all_tag_list
    %h3 タグ一覧
    = link_to("[全てのタグ一覧]", tags_path, :class => "tag_list_link")
    %br
    - tags.each do |t|
      %span.tag= link_to(t.value, search_pasokaras_path(:filter => @filters ? @filters.join("+") + "+#{t.value}" : "#{t.value}", :query => params[:query], :field => params[:field])) + "(#{t.count})"

app/views/layouts/_navi_bar.html.haml
%ul#menu
  %li= link_to "ホーム", root_path, :id => "home"
  %li= link_to "予約確認", queues_path, :id => "queue"
  %li= link_to "りれき", history_index_path, :id => "history"
  - if user_signed_in?
    %li= link_to("お気に入り", favorite_pasokaras_path, :id => "favorite")
    %li= link_to("設定変更", edit_user_registration_path, :id => "user_edit")
  %li= link_to("使い方", help_usage_path, :id => "usage")
  - if user_signed_in?
    %li= link_to("再生開始", play_pasokaras_path, :id => "launch")

app/views/layouts/_search_header.html.haml
%nav
  = render :partial => "layouts/navi_bar"
%br
= render :partial => "layouts/solr_search_form"
- unless @no_tag_load || @header_tags.nil?
  = render :partial => "layouts/header_tag_list", :locals => {:tags => @header_tags}
%hr

app/views/layouts/_solr_search_form.html.haml
#solr_search
  .search
    = form_tag search_pasokaras_path do
      %label Solr検索
      = text_field_tag("query", params[:query], :size => 56) 
      = select_tag("field", options_for_select([["全て", "a"], ["名前", "n"], ["タグ", "t"], ["説明", "d"], ["Raw", "r"]], params[:field]))
      = submit_tag("Search")

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html;charset=UTF-8", "http-equiv" => "content-type"}/
    %meta{:content => "noindex,nofollow", :name => "robots"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    - if request.iphone?
      %meta{:content => "width=800, initial-scale=0.4", :name => "viewport"}/
    - elsif request.ipad?
      %meta{:content => "width=800, initial-scale=1.0", :name => "viewport"}/
    %title Pasokara Player
    :javascript
      $(document).ready(function() {
        $("img.thumb").lazyload({
          effect : "fadeIn"
        });

        $('div.title a.queue_link').linkwrapper();
        $('li.queue a').linkwrapper();

        $('#site_title').FontEffect({
           mirror: true,
           mirrorColor: "#FFFFFF",
           mirrorOffset: -15,
           mirrorHeight: 70,
           gradient: true,
           gradientFromTop: true,
           gradientColor: "#AAA",
           gradientPosition: 20,
           gradientLength: 50,
           gradientSteps: 20
        });
      });
  %body
    %header
    %h1#site_title
      %span> P
      asokara Player
    - if current_user.try(:admin)
      #nico_list_setting
        = link_to("ダウンロードリスト編集", nico_lists_path)
    #user_info
      - if current_user
        %span.login_user= "現在のログインユーザー: " + current_user.nickname
      = link_to("ユーザー切り替え", new_user_session_path, :class => "user_link") + ":"
      = link_to("ユーザー作成", new_user_registration_path, :class => "user_link") if current_user && current_user.name != "guest"
    - if current_user.try(:admin)
      #encode_mode_info
        %span.encode_mode 現在のモード: #{session[:encode_mode]}
        = link_to "切り替え", change_encode_mode_pasokaras_path
        .clearfix
    - if flash[:notice]
      .notification= flash[:notice]
    - if flash[:error]
      .error_notification= flash[:error]
    - if flash[:alert]
      .error_notification= flash[:alert]
    #main
      = render 'layouts/search_header'
      %article
      = yield
      %hr
      %footer
        &copy; Tomohiro Hashidate